# SAM template for CodeBuild
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple AWS Lambda for searching dark souls weapons within a DynamoDB table.
Resources:
  GetBooksFx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/get-weapons-fx-1.0-SNAPSHOT.jar
      Handler: com.revature.get_weapons.GetWeaponsHandler
      Runtime: java8.al2
      Description: Java function
      MemorySize: 256
      Timeout: 30
      Tracing: Active
      Policies:
      - arn:aws:iam::638686461389:policy/get-weapons-policy