package com.revature.get_weapons;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.Map;

@Data
@DynamoDBTable(tableName = "dark-souls-weapons")
public class Weapon {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String weaponType;

    @DynamoDBAttribute
    private String weaponName;

    @DynamoDBAttribute
    private int physicalDamage;

    @DynamoDBAttribute
    private int magicalDamage;

    @DynamoDBAttribute
    private int fireDamage;

    @DynamoDBAttribute
    private int lightningDamage;

    @DynamoDBAttribute
    private Map<String, String> parameterBonuses;

}
